version: '3.3'
services:
  evolvestd_1:
    build: .
    ports:
      - "18762:8762"
      - "18763:8763"
      - "18080:8080"
    restart: always
  evolvestd_2:
    build: .
    ports:
      - "28762:8762"
      - "28763:8763"
      - "28080:8080"
    restart: always
  evolvestd_3:
    build: .
    ports:
      - "38762:8762"
      - "38763:8763"
      - "38080:8080"
    restart: always
